#!/usr/bin/env bash
set -euo pipefail
# shellcheck disable=SC2155  # shellcheck-format ignore for Sonar rule shell:S6573
# NOSONAR: Sonar rule shell:S6573 is acknowledged and ignored for this installer script.

# Install Firebird client libraries and the Python Firebird driver on Ubuntu.
# If CMake config fails (common with policy/version differences), fall back to autogen/configure.
# Try installing tommath/tomcrypt dev packages; if configure still fails, retry with builtin tommath/tomcrypt.
# If 'make install' fails (packaging step), attempt to extract generated buildroot or copy built files manually.
# Default: FIREBIRD_VERSION=5.0.4

: "${FIREBIRD_VERSION:=5.0.4}"

if [ "$(id -u)" -ne 0 ]; then
  SUDO=sudo
else
  SUDO=
fi

echo "Installing build dependencies (apt)..."
$SUDO apt-get update -qq
$SUDO apt-get install -y --no-install-recommends \
  build-essential cmake pkg-config wget ca-certificates \
  autoconf automake libtool python3-dev python3-pip libssl-dev libicu-dev \
  libreadline-dev libxml2-dev zlib1g-dev git libtommath-dev libtomcrypt-dev || true

WORKDIR=$(mktemp -d)
trap 'test -n "" && true' EXIT
cd "$WORKDIR"

echo "Downloading Firebird source v${FIREBIRD_VERSION}..."
wget --https-only --secure-protocol=TLSv1_2 --max-redirect=0 -q -O firebird.tar.gz "https://codeload.github.com/FirebirdSQL/firebird/tar.gz/refs/tags/v${FIREBIRD_VERSION}"
if [ ! -s firebird.tar.gz ]; then
  echo "Failed to download source tarball. Check FIREBIRD_VERSION or network." >&2
  exit 2
fi

echo "Extracting source..."
tar xzf firebird.tar.gz
SRC_DIR=$(find . -maxdepth 1 -type d -name "firebird-*" -print -quit)
if [ -z "$SRC_DIR" ]; then
  echo "Could not find extracted source directory." >&2
  exit 3
fi
cd "$SRC_DIR"

# Try CMake build first. If configure fails, fall back to autogen/configure.
FALLBACK=0
if command -v cmake >/dev/null 2>&1 && ( [ -f CMakeLists.txt ] || [ -d cmake ] ); then
  echo "Attempting to build Firebird client with CMake (client-only)..."
  mkdir -p build && cd build
  # Pass a policy hint to reduce failures on older project CMake setups; if this fails we'll fallback.
  if cmake .. -DCLIENT_ONLY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_POLICY_VERSION_MINIMUM=3.5; then
    make -j"$(nproc)"
    # Prefer not to run cmake --install which may invoke packaging; instead try to install later if needed
    if $SUDO cmake --install .; then
      INSTALLED=1
    else
      INSTALLED=0
    fi
  else
    echo "CMake configure failed. Falling back to autogen/configure build..."
    FALLBACK=1
    cd ..
  fi
else
  FALLBACK=1
fi

if [ "$FALLBACK" -eq 1 ]; then
  echo "Building Firebird client with autogen/configure (client-only)..."
  chmod +x ./autogen.sh || true
  ./autogen.sh || true
  # Try normal configure first
  if ./configure --enable-client-only --prefix=/usr/local; then
    echo "Configure succeeded." 
  else
    echo "Configure failed. Retrying configure with --with-builtin-tommath and --with-builtin-tomcrypt..."
    if ./configure --enable-client-only --prefix=/usr/local --with-builtin-tommath --with-builtin-tomcrypt; then
      echo "Configure with builtin tommath/tomcrypt succeeded."
    else
      echo "Configure failed even with builtin tommath/tomcrypt. Exiting." >&2
      exit 4
    fi
  fi
  make -j"$(nproc)"
  # Try make install; packaging step sometimes fails (install.sh missing). If it fails, attempt to extract buildroot or copy built artifacts.
  if $SUDO make install; then
    echo "make install succeeded"
  else
    echo "make install failed; attempting fallback installation from generated build artifacts..."
    # Search for buildroot tarballs generated by packaging
    set +e
    TARS=$(find . -path "*/gen/*" -type f -name 'buildroot.tar.gz' 2>/dev/null || true)
    if [ -n "$TARS" ]; then
      for t in $TARS; do
        echo "Extracting $t to / (requires sudo)..."
        $SUDO tar -C / -xzf "$t" || echo "Failed to extract $t" >&2
      done
    else
      # Search for buildroot directories
      BRDIRS=$(find . -path "*/gen/*" -type d -name 'buildroot' 2>/dev/null || true)
      if [ -n "$BRDIRS" ]; then
        for d in $BRDIRS; do
          echo "Copying contents of $d to / (requires sudo)..."
          $SUDO cp -a "$d/." / || echo "Failed to copy from $d" >&2
        done
      else
        # Last resort: copy libraries and headers manually
        echo "No buildroot found. Trying to locate built libraries and headers to install manually..."
        LIBS=$(find . -type f -name 'libfbclient.so*' -print -quit 2>/dev/null || true)
        if [ -n "$LIBS" ]; then
          for lib in $(find . -type f -name 'libfbclient.so*' 2>/dev/null); do
            echo "Installing $lib -> /usr/local/lib/"
            $SUDO install -m 755 "$lib" /usr/local/lib/ || $SUDO cp -a "$lib" /usr/local/lib/
          done
        fi
        # headers
        for hdr in $(find . -type f -path '*/include/firebird/*' 2>/dev/null || true); do
          echo "Installing header $hdr"
          $SUDO mkdir -p /usr/local/include/firebird
          $SUDO cp -a "$hdr" /usr/local/include/firebird/
        done
      fi
    fi
    set -e
    # make sure libraries are visible
    $SUDO ldconfig || true
  fi
fi

# Strip unneeded symbols from installed libraries (best-effort)
$SUDO bash -c 'find /usr/local -type f -name "*.so*" -exec strip --strip-unneeded {} + 2>/dev/null || true'

# Install Python Firebird driver
python3 -m pip install --upgrade pip
$SUDO python3 -m pip install --upgrade firebird-driver

# Cleanup workspace; use sudo in case some files are root-owned
$SUDO rm -rf "$WORKDIR" || true

echo "Firebird client and Python driver installation complete. Libraries installed to /usr/local (libs under /usr/local/lib)"
