# Project identity
sonar.projectKey=lhotakj_kinetiqo
sonar.projectName=Kinetiqo
sonar.projectVersion=2.0

# Sources / tests
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.14

# Coverage (generate coverage.xml during CI and point Sonar to it)
sonar.python.coverage.reportPaths=coverage.xml

# Optional analysis tuning
sonar.sourceEncoding=UTF-8

# Exclude web templates, static assets and third-party vendor files from static analysis
# Templates contain a mix of HTML and inline JS that generates many false positives for Sonar
sonar.exclusions=**/web/templates/**,**/web/static/**,**/static/**,**/build/**,**/docs/**,**/dist/**,**/*.pyc,**/__pycache__/**,**/node_modules/**,src/kinetiqo/web/static/**


sonar.issue.ignore.multicriteria.webapp-bind.ruleKey=python:S8392
sonar.issue.ignore.multicriteria.webapp-bind.resourceKey=src/kinetiqo/web/app.py

sonar.issue.ignore.multicriteria=webapp-bind,web-s5725,docker,docker-deps,python-complexity,duplicate-strings,shell-s6573,python-8786,pythonsecurity-s5145,javascript-s2004,html-s2004,javascript-s7740,javascript-s2486,python-s1192,python-complexity,python-s8392,javascript-s7773,javascript-s7761,css-s7924,githubactions-s7637,pythonsecurity-s5145

sonar.issue.ignore.multicriteria.web-s5725.ruleKey=web:S5725
sonar.issue.ignore.multicriteria.web-s5725.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.docker.ruleKey=docker:S6471
sonar.issue.ignore.multicriteria.docker.resourceKey=**/Dockerfile*.*

sonar.issue.ignore.multicriteria.docker-deps.ruleKey=docker:S8544
sonar.issue.ignore.multicriteria.docker-deps.resourceKey=**/Dockerfile*.*

sonar.issue.ignore.multicriteria.python-complexity.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.python-complexity.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.duplicate-strings.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.duplicate-strings.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.shell-s6573.ruleKey=shell:S6573
sonar.issue.ignore.multicriteria.shell-s6573.resourceKey=**/*.sh

sonar.issue.ignore.multicriteria.python-8786.ruleKey=python:8786
sonar.issue.ignore.multicriteria.python-8786.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.pythonsecurity-s5145.ruleKey=pythonsecurity:S5145
sonar.issue.ignore.multicriteria.pythonsecurity-s5145.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.javascript-s2004.ruleKey=javascript:S2004
sonar.issue.ignore.multicriteria.javascript-s2004.resourceKey=**/*.js

sonar.issue.ignore.multicriteria.html-s2004.ruleKey=javascript:S2004
sonar.issue.ignore.multicriteria.html-s2004.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.javascript-s7740.ruleKey=javascript:S7740
sonar.issue.ignore.multicriteria.javascript-s7740.resourceKey=**/*.html


sonar.issue.ignore.multicriteria.python-s1192.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.python-s1192.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.python-complexity.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.python-complexity.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.python-s8392.ruleKey=python:S8392
sonar.issue.ignore.multicriteria.python-s8392.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.javascript-s2486.ruleKey=javascript:S2486
sonar.issue.ignore.multicriteria.javascript-s2486.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.javascript-s2486.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.javascript-s7773.ruleKey=javascript:S7773
sonar.issue.ignore.multicriteria.javascript-s7773.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.javascript-s7761.ruleKey=javascript:S7761
sonar.issue.ignore.multicriteria.javascript-s7761.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.css-s7924.ruleKey=css:S7924
sonar.issue.ignore.multicriteria.css-s7924.resourceKey=**/*.css

sonar.issue.ignore.multicriteria.githubactions-s7637.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.githubactions-s7637.resourceKey=**/*.yaml

sonar.issue.ignore.multicriteria.pythonsecurity-s5145.ruleKey=pythonsecurity:S5145
sonar.issue.ignore.multicriteria.pythonsecurity-s5145.resourceKey=**/*.py
