# SonarQube project configuration for Kinetiqo
# See https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/ for details
sonar.projectKey=kinetiqo
sonar.projectName=Kinetiqo
# sonar.projectVersion=1.0

# Source directories
sonar.sources=src

# Exclude web templates, static assets and third-party vendor files from static analysis
# Templates contain a mix of HTML and inline JS that generates many false positives for Sonar
sonar.exclusions=**/web/templates/**, **/web/static/**, **/static/**, **/build/**, **/docs/**


sonar.issue.ignore.multicriteria=webapp-bind
sonar.issue.ignore.multicriteria.webapp-bind.ruleKey=python:S8392
sonar.issue.ignore.multicriteria.webapp-bind.resourceKey=src/kinetiqo/web/app.py

sonar.issue.ignore.multicriteria=web-s5725,docker,docker-deps,python-complexity,duplicate-strings,shell-s6573,python-8786,pythonsecurity-s5145,javascript-s2004,html-s2004,javascript-s7740

sonar.issue.ignore.multicriteria.web-s5725.ruleKey=web:S5725
sonar.issue.ignore.multicriteria.web-s5725.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.docker.ruleKey=docker:S6471
sonar.issue.ignore.multicriteria.docker.resourceKey=**/Dockerfile*.*

sonar.issue.ignore.multicriteria.docker-deps.ruleKey=docker:S8544
sonar.issue.ignore.multicriteria.docker-deps.resourceKey=**/Dockerfile*.*

sonar.issue.ignore.multicriteria.python-complexity.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.python-complexity.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.duplicate-strings.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.duplicate-strings.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.shell-s6573.ruleKey=shell:S6573
sonar.issue.ignore.multicriteria.shell-s6573.resourceKey=**/*.sh

sonar.issue.ignore.multicriteria.python-8786.ruleKey=python:8786
sonar.issue.ignore.multicriteria.python-8786.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.pythonsecurity-s5145.ruleKey=pythonsecurity:S5145
sonar.issue.ignore.multicriteria.pythonsecurity-s5145.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.javascript-s2004.ruleKey=javascript:S2004
sonar.issue.ignore.multicriteria.javascript-s2004.resourceKey=**/*.js

sonar.issue.ignore.multicriteria.html-s2004.ruleKey=javascript:S2004
sonar.issue.ignore.multicriteria.html-s2004.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.javascript-s7740.ruleKey=javascript:S7740
sonar.issue.ignore.multicriteria.javascript-s7740.resourceKey=**/*.html

sonar.sourceEncoding=UTF-8
