{
 "title": "QuestDB Basic Dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Total Distance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(distance) / 1000.0 as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Total Elevation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(total_elevation_gain) as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Highest HR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(heartrate) as value FROM streams WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Average HR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(heartrate) as value FROM streams WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Highest elevation gained",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_elevation_gain, name, activity_id FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide') ORDER BY total_elevation_gain DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Rides by Sport",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sport as metric, count(*) as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide') GROUP BY sport"
    }
   ]
  },
  {
   "title": "Average distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(distance) / 1000.0 as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Average elevation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(total_elevation_gain) as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Longest ride",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distance / 1000.0 as value, name, activity_id FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide') ORDER BY distance DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Total rides",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Average Cadence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(average_cadence) as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide')"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, distance / 1000.0 as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide') ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Elevation gain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, total_elevation_gain as value FROM activities WHERE $__timeFilter(timestamp) AND sport IN ('Ride', 'VirtualRide', 'GravelRide') ORDER BY timestamp"
    }
   ]
  }
 ]
}